kernel: add ksu_sys_umount function for < 5.9.0 kernels
ksu_sys_umount its implemented but only for <4.17 kernels, causing compilation problems in kernels like 5.4.

compilation log:

../drivers/kernelsu/infra/su_mount_ns.c:125:16: error: implicit declaration of function 'ksu_sys_unshare' [-Werror,-Wimplicit-function-declaration]
    long ret = ksu_sys_unshare(CLONE_NEWNS);
               ^
../drivers/kernelsu/infra/su_mount_ns.c:125:16: note: did you mean 'ksys_unshare'?
../include/linux/syscalls.h:1251:5: note: 'ksys_unshare' declared here
int ksys_unshare(unsigned long unshare_flags);
    ^
1 error generated.
make[3]: *** [../scripts/Makefile.build:288: drivers/kernelsu/infra/su_mount_ns.o] Error 1
make[3]: *** Waiting for unfinished jobs....